user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections 1024;  # Максимальное количество соединений на рабочий процесс
}


http {

    server {
        listen 80;
        server_name nails-tango.online;

        location /.well-known/acme-challenge/ {
            root /var/www/html;
            index index.html;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }

    # Второй сервер для HTTPS (порт 443)
   server {
        listen 443 ssl;
        server_name nails-tango.online;

        ssl_certificate /etc/letsencrypt/live/nails-tango.online/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/nails-tango.online/privkey.pem;

        location /webhook {
            proxy_pass http://bot:8777;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location / {
            root /var/www/html;
            index index.html;
            try_files $uri $uri/ =404;
        }
    }
}